export const GET_ALL_TEMPERAMENTS = "GET_ALL_TEMPERAMENTS";
export const GET_ALL_BREEDS = "GET_ALL_BREEDS";
export const REMOVE_BREED = "REMOVE_BREED";
export const FILTER_BY_TEMPERAMENTS = "FILTER_BY_TEMPERAMENTS";
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN";
export const ORDER_BY_WEIGHT = "ORDER_BY_WEIGHT";
export const ALPHABETICAL_ORDER = "ALPHABETICAL_ORDER";
export const SEARCH_BY_NAME = "SEARCH_BY_NAME"; 